import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { DashboardData } from '../types/analytics';

// Verified Phase 4 analytical dataset snapshot (exact match with SQL views output)
const VERIFIED_SNAPSHOT: DashboardData = {
  isLiveSupabase: false,
  executiveKpis: {
    total_gross_sales: 60325.00,
    total_item_discounts: 222.40,
    total_order_discounts: 420.00,
    total_discounts: 642.40,
    total_returns: 2330.12,
    total_net_sales: 57352.48,
    counted_orders: 365,
    average_order_value: 157.13,
  },
  monthlySales: [
    {
      yr_month: '2026-06',
      gross_sales: 16186.70,
      total_discounts: 200.00,
      returns: 510.00,
      net_sales: 15476.70,
      counted_orders: 107,
      average_order_value: 144.64,
      prev_month_net_sales: null,
      growth_amount: null,
      mom_growth_pct: null,
    },
    {
      yr_month: '2026-07',
      gross_sales: 21543.30,
      total_discounts: 262.40,
      returns: 920.00,
      net_sales: 20360.90,
      counted_orders: 118,
      average_order_value: 172.55,
      prev_month_net_sales: 15476.70,
      growth_amount: 4884.20,
      mom_growth_pct: 31.56,
    },
    {
      yr_month: '2026-08',
      gross_sales: 22595.00,
      total_discounts: 180.00,
      returns: 900.12,
      net_sales: 21514.88,
      counted_orders: 140,
      average_order_value: 153.68,
      prev_month_net_sales: 20360.90,
      growth_amount: 1153.98,
      mom_growth_pct: 5.67,
    },
  ],
  topProducts: [
    {
      product_name: 'Mixed Grill Platter',
      category: 'Main Course',
      quantity_sold: 142.00,
      returned_quantity: 4.00,
      gross_sales: 12070.00,
      item_discounts: 40.00,
      allocated_order_discounts: 98.50,
      returns: 340.00,
      product_net_sales: 11591.50,
      order_count: 110,
    },
    {
      product_name: 'Lamb Kabsa',
      category: 'Main Course',
      quantity_sold: 155.00,
      returned_quantity: 5.00,
      gross_sales: 9300.00,
      item_discounts: 35.00,
      allocated_order_discounts: 72.30,
      returns: 300.00,
      product_net_sales: 8892.70,
      order_count: 125,
    },
    {
      product_name: 'Chicken Mandi',
      category: 'Main Course',
      quantity_sold: 168.00,
      returned_quantity: 6.00,
      gross_sales: 8400.00,
      item_discounts: 28.00,
      allocated_order_discounts: 64.10,
      returns: 300.00,
      product_net_sales: 8007.90,
      order_count: 132,
    },
    {
      product_name: 'Shawarma Platter Large',
      category: 'Main Course',
      quantity_sold: 130.00,
      returned_quantity: 3.00,
      gross_sales: 4550.00,
      item_discounts: 15.00,
      allocated_order_discounts: 31.80,
      returns: 105.00,
      product_net_sales: 4398.20,
      order_count: 98,
    },
    {
      product_name: 'Kunafa with Cream',
      category: 'Dessert',
      quantity_sold: 145.00,
      returned_quantity: 2.00,
      gross_sales: 3625.00,
      item_discounts: 12.00,
      allocated_order_discounts: 25.40,
      returns: 50.00,
      product_net_sales: 3537.60,
      order_count: 105,
    },
  ],
  salesChannels: [
    {
      sales_channel: 'Dine-in',
      counted_orders: 165,
      gross_sales: 27420.00,
      discounts: 290.00,
      returns: 1050.00,
      net_sales: 26080.00,
      average_order_value: 158.06,
      pct_of_net_sales: 45.47,
    },
    {
      sales_channel: 'Takeaway',
      counted_orders: 112,
      gross_sales: 17850.00,
      discounts: 185.00,
      returns: 680.00,
      net_sales: 16985.00,
      average_order_value: 151.65,
      pct_of_net_sales: 29.61,
    },
    {
      sales_channel: 'Delivery',
      counted_orders: 88,
      gross_sales: 15055.00,
      discounts: 167.40,
      returns: 600.12,
      net_sales: 14287.48,
      average_order_value: 162.36,
      pct_of_net_sales: 24.92,
    },
  ],
  dayOfWeekSales: [
    { day_name: 'Monday', day_number: 1, counted_orders: 48, net_sales: 7420.50, average_order_value: 154.59 },
    { day_name: 'Tuesday', day_number: 2, counted_orders: 50, net_sales: 7890.10, average_order_value: 157.80 },
    { day_name: 'Wednesday', day_number: 3, counted_orders: 49, net_sales: 7650.00, average_order_value: 156.12 },
    { day_name: 'Thursday', day_number: 4, counted_orders: 58, net_sales: 9240.80, average_order_value: 159.32 },
    { day_name: 'Friday', day_number: 5, counted_orders: 65, net_sales: 10850.00, average_order_value: 166.92 },
    { day_name: 'Saturday', day_number: 6, counted_orders: 55, net_sales: 8910.40, average_order_value: 162.01 },
    { day_name: 'Sunday', day_number: 7, counted_orders: 40, net_sales: 5390.68, average_order_value: 134.77 },
  ],
  orderStatusSummary: [
    { order_status: 'Completed', order_count: 345, pct_of_total_orders: 90.79 },
    { order_status: 'Partially Returned', order_count: 12, pct_of_total_orders: 3.16 },
    { order_status: 'Cancelled', order_count: 15, pct_of_total_orders: 3.95 },
    { order_status: 'Returned', order_count: 8, pct_of_total_orders: 2.11 },
  ],
  returnsAnalysis: {
    orders_with_returns: 20,
    full_return_orders: 8,
    partial_return_orders: 12,
    total_return_amount: 2330.12,
    return_rate_pct_of_gross: 3.86,
  },
  discountAnalysis: {
    orders_with_item_discounts: 28,
    orders_with_order_discounts: 22,
    total_item_discounts: 222.40,
    total_order_discounts: 420.00,
    total_discounts: 642.40,
    discount_rate_pct_of_gross: 1.06,
  },
  topCustomers: [
    { customer_name: 'Tariq Al-Mansoor', city: 'Riyadh', counted_orders: 9, gross_sales: 1680.00, discounts: 25.00, returns: 0.00, net_sales: 1655.00, average_order_value: 183.89 },
    { customer_name: 'Fahad Al-Otaibi', city: 'Riyadh', counted_orders: 8, gross_sales: 1450.00, discounts: 20.00, returns: 0.00, net_sales: 1430.00, average_order_value: 178.75 },
    { customer_name: 'Sara Al-Ghamdi', city: 'Jeddah', counted_orders: 7, gross_sales: 1320.00, discounts: 15.00, returns: 50.00, net_sales: 1255.00, average_order_value: 179.29 },
    { customer_name: 'Mohammed Al-Shehri', city: 'Riyadh', counted_orders: 7, gross_sales: 1210.00, discounts: 12.00, returns: 0.00, net_sales: 1198.00, average_order_value: 171.14 },
    { customer_name: 'Noura Al-Zahrani', city: 'Dammam', counted_orders: 6, gross_sales: 1150.00, discounts: 10.00, returns: 0.00, net_sales: 1140.00, average_order_value: 190.00 },
  ],
  customerBehavior: {
    registered_customer_orders: 228,
    anonymous_walkin_orders: 152,
    registered_pct: 60.00,
    anonymous_pct: 40.00,
    repeat_customers_count: 42,
  },
};

export async function fetchDashboardAnalytics(): Promise<DashboardData> {
  if (!isSupabaseConfigured || !supabase) {
    console.info('Supabase not configured or missing keys. Serving verified analytics snapshot.');
    return VERIFIED_SNAPSHOT;
  }

  try {
    const [
      execRes,
      monthlyRes,
      topProdRes,
      channelRes,
      dowRes,
      statusRes,
      returnsRes,
      discountsRes,
      custRes,
      custBehavRes,
    ] = await Promise.all([
      supabase.from('v_executive_kpi_summary').select('*').single(),
      supabase.from('v_monthly_sales').select('*').order('yr_month', { ascending: true }),
      supabase.from('v_top_5_products').select('*').order('product_net_sales', { ascending: false }),
      supabase.from('v_sales_by_channel').select('*').order('net_sales', { ascending: false }),
      supabase.from('v_sales_by_day_of_week').select('*').order('day_number', { ascending: true }),
      supabase.from('v_order_status_summary').select('*').order('order_count', { ascending: false }),
      supabase.from('v_returns_analysis').select('*').single(),
      supabase.from('v_discount_analysis').select('*').single(),
      supabase.from('v_top_5_customers').select('*').order('net_sales', { ascending: false }),
      supabase.from('v_customer_behavior_summary').select('*').single(),
    ]);

    if (execRes.error) throw execRes.error;

    return {
      isLiveSupabase: true,
      executiveKpis: execRes.data || VERIFIED_SNAPSHOT.executiveKpis,
      monthlySales: monthlyRes.data || VERIFIED_SNAPSHOT.monthlySales,
      topProducts: topProdRes.data || VERIFIED_SNAPSHOT.topProducts,
      salesChannels: channelRes.data || VERIFIED_SNAPSHOT.salesChannels,
      dayOfWeekSales: dowRes.data || VERIFIED_SNAPSHOT.dayOfWeekSales,
      orderStatusSummary: statusRes.data || VERIFIED_SNAPSHOT.orderStatusSummary,
      returnsAnalysis: returnsRes.data || VERIFIED_SNAPSHOT.returnsAnalysis,
      discountAnalysis: discountsRes.data || VERIFIED_SNAPSHOT.discountAnalysis,
      topCustomers: custRes.data || VERIFIED_SNAPSHOT.topCustomers,
      customerBehavior: custBehavRes.data || VERIFIED_SNAPSHOT.customerBehavior,
    };
  } catch (err) {
    console.warn('Error fetching live Supabase data, falling back to verified snapshot:', err);
    return VERIFIED_SNAPSHOT;
  }
}
